baseURL = "http://blog.cc-cloud.top/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "Bahtyar's Blog"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FeelIt"

[params]
  # FeelIt 主题版本
  version = "1.0.X"
# 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
    # FeelIt 新增 | 0.2.0页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = ""
      # 标题名称
      name = ""
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # FeelIt 新增 | 0.2.5是否为标题显示打字机动画
      typeit = false
      # FeelIt 新增 | 1.0.0是否显示RSS图标
      rss = true

  [params.footer]
    enable = true
    # FeelIt 新增 | 0.2.0自定义内容 (支持 HTML 格式)
    custom = ''
    # FeelIt 新增 | 0.2.0是否显示 Hugo 和主题信息
    hugo = true
    # FeelIt 新增 | 0.2.0是否显示版权信息
    copyright = true
    # FeelIt 新增 | 0.2.0是否显示作者
    author = true
    # 网站创立年份
    since = 2024
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    # icp = ""
    # 许可协议信息 (支持 HTML 格式)
    # license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "index"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "首页"
    url = "/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 4

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/khusika/FeelIt/issues/158)
    noClasses = false

