baseURL = "http://blog.cc-cloud.top/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "Bahtyar's Blog"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FeelIt"

[params]
  # FeelIt 主题版本
  version = "1.0.X"
  # LoveIt theme version
  # site default theme ("light", "dark", "auto")
  # 网站默认主题 ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = "https://github.com/Bahtya/Bahtya.github.io"
  # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # date format
  # 日期格式
  dateFormat = "2006-01-02"
  # website images for Open Graph and Twitter Cards
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = ["/logo.png"]
  # site description
  description = "a"
  # site keywords
  keywords = ["K_TECH"]
  # whether to enable CSS and JS source mapping
  SourceMap = false
# 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
    # FeelIt 新增 | 0.2.0页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = ""
      # 标题名称
      name = ""
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # FeelIt 新增 | 0.2.5是否为标题显示打字机动画
      typeit = false
      # FeelIt 新增 | 1.0.0是否显示RSS图标
      rss = true

  [params.footer]
    enable = true
    # FeelIt 新增 | 0.2.0自定义内容 (支持 HTML 格式)
    custom = ''
    # FeelIt 新增 | 0.2.0是否显示 Hugo 和主题信息
    hugo = true
    # FeelIt 新增 | 0.2.0是否显示版权信息
    copyright = true
    # FeelIt 新增 | 0.2.0是否显示作者
    author = true
    # 网站创立年份
    since = 2024
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    # icp = ""
    # 许可协议信息 (支持 HTML 格式)
    # license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "index"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "首页"
    url = "/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 4

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/khusika/FeelIt/issues/158)
    noClasses = false

# 主页配置
[params.home]
  # FeelIt 新增 | 0.2.0 RSS 文章数目
  rss = 10
  # 主页个人信息
  [params.home.profile]
    enable = true
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # 主页显示头像的 URL
    avatarURL = "/images/avatar.png"
    # FeelIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
    title = ""
    # 主页显示的网站副标题
    subtitle = "这是我的全新 Hugo 网站"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = true
    # FeelIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
    disclaimer = ""
  # 主页文章列表
  [params.home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 6
    # FeelIt 更改 | 1.0.1 display image-preview
    imagePreview = true
    # FeelIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
    # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
    defaultHiddenFromHomePage = false

[params.page]
    # FeelIt 新增 | 0.2.0 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # FeelIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # FeelIt 新增 | 0.2.0 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = false
    # FeelIt 新增 | 0.2.0 是否使用 ruby 扩展语法
    ruby = true
    # FeelIt 新增 | 0.2.0 是否使用 fraction 扩展语法
    fraction = true
    # FeelIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
    fontawesome = true
    # FeelIt 新增 | 1.0.0 是否使用 fontawesome 作为CDN源
    cdnfontawesome = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
    # FeelIt 新增 | 1.0.0 是否显示链接以改善文章
    improveArticle = ""
    # FeelIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
    rssFullText = false
    # FeelIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # FeelIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
      keepStatic = true
      # 是否使侧边目录自动折叠展开
      auto = true
    # FeelIt 新增 | 0.2.0